- name: Remove any existing local directory for cas-overlay-demo
  file:
    path: /usr/local/ozp/build/cas-overlay-demo
    state: absent
  become: true
  become_user: ozp

- name: Download source from GitLab tag
  when: (not offline)
  git:
    repo: http://dev1.vistronix.com:9080/ozp/cas-overlay-demo.git
    dest: /usr/local/ozp/build/cas-overlay-demo
    version: 4.2.x
  become: true
  become_user: ozp

- name: Build CAS client and manager
  shell:  /usr/local/apache-maven/bin/mvn clean install
  args:
    chdir: /usr/local/ozp/build/cas-overlay-demo
  become: true
  become_user: ozp

- name: Run CAS client and manager
  shell:  /usr/local/apache-maven/bin/mvn jetty:run &
  args:
    chdir: /usr/local/ozp/build/cas-overlay-demo/cas-overlay-server-demo
  become: true
  become_user: ozp
