- name: Remove any existing local directory for cas-overlay-demo
  file:
    path: /usr/local/ozp/build/cas-overlay-demo
    state: absent
  become: true
  become_user: ozp

- name: Download source from GitLab tag
  when: (not offline)
  git:
    repo: http://dev1.vistronix.com:9080/ozp/cas-overlay-demo.git
    dest: /usr/local/ozp/build/cas-overlay-demo
  become: true
  become_user: ozp

- name: Checkout git branch or tag name
  command: git checkout 4.2.x
  args:
    chdir: /usr/local/ozp/build/cas-overlay-demo
  become: true
  become_user: ozp

- name: Build CAS client and manager
  shell:  mvn clean install
  args:
    chdir: /usr/local/ozp/build/cas-overlay-demo
  become: true

- name: Run CAS client and manager
  shell:  mvn jetty:run
  args:
    chdir: /usr/local/ozp/build/cas-overlay-demo/cas-overlay-server-demo
  become: true
