- name: Remove any existing local directory for cas-artifacts
  file:
    path: /opt/cas-artifacts
    state: absent
  become: true
  become_method: sudo

- name: Download source from GitLab tag
  when: (not offline)
  git:
    repo: "{{ git_host }}/{{ git_cas_url }}"
    dest: /opt/cas-artifacts
    version: master
  become: true
  become_method: sudo

- name: Remove existing CAS config foler
  file:
    path: /etc/cas
    state: absent
  become: true
  become_method: sudo

- name: Create CAS config folder
  file:
    path: /etc/cas
    state: directory
    owner: tomcat
    group: tomcat
  become: true
  become_method: sudo

- name: Move CAS Config
  template: src=cas.properties dest=/etc/cas/ owner=tomcat group=tomcat
  become: true
  become_method: sudo

- name: Move deployerConfigContextAD.xml
  copy: src=deployerConfigContext-AD.xml dest=/etc/cas/deployerConfigContext.xml owner=tomcat group=tomcat
  when: enable_ad
  become: true
  become_method: sudo

- name: Move deployerConfigContext.xml
  copy: src=deployerConfigContext.xml dest=/etc/cas/deployerConfigContext.xml owner=tomcat group=tomcat
  when: not enable_ad
  become: true
  become_method: sudo

- name: Stop Tomcat
  service: name=tomcat state=stopped
  become: true
  become_method: sudo

- name: Remove existing CAS war
  file:
    path: /opt/apache-tomcat-7.0.61/webapps/cas.war
    state: absent
  become: true
  become_method: sudo

- name: Remove existing CAS Tomcat deployment
  file:
    path: /opt/apache-tomcat-7.0.61/webapps/cas
    state: absent
  become: true
  become_method: sudo

- name: Move CAS war
  shell: cp /opt/cas-artifacts/cas.war /opt/apache-tomcat-7.0.61/webapps/cas.war ; chown tomcat:tomcat /opt/apache-tomcat-7.0.61/webapps/cas.war
  become: true
  become_method: sudo

- name:	Start Tomcat
  service: name=tomcat state=started
  become: true
  become_method: sudo
