- name: Remove any existing local directory for cas-artifacts
  file:
    path: /opt/cas-artifacts
    state: absent
  become: true
  become_method: sudo

- name: Download source from GitLab tag
  when: (not offline)
  git:
    repo: "{{ git_host }}/{{ git_cas_url }}"
    dest: /opt/cas-artifacts
    version: master
  become: true
  become_method: sudo

- name: Create CAS config folder
  file:
    path: /etc/cas
    state: directory
  become: true
  become_method: sudo

- name: Move CAS Config
  template: src=cas.properties dest=/etc/cas/
  become: true
  become_method: sudo

- name: Move CAS war
  shell: cp /opt/cas-artifacts/cas.war /opt/apache-tomcat-7.0.61/webapps/cas.war ; chown tomcat:tomcat /opt/apache-tomcat-7.0.61/webapps/cas.war
  become: true
  become_method: sudo
