---
# Active Directory Settings: leave following setting blank if not using AD, otherwise replace below samples with installation specific data as needed
ldap_ldapUrl: ldap://localhost:1389
ldap_useSsl: false
ldap_useStartTLS: false
ldap_connectTimeout: 5000
ldap_baseDn: ou=people,dc=example,dc=org
ldap_userFilter: cn={user}
ldap_subtreeSearch: true
ldap_usePasswordPolicy: false
ldap_bindDn: cn=Directory Manager,dc=example,dc=org
ldap_bindCredential: Password
ldap_principalAttributeId: uid

# This is a list of static users to provide for CAS instead of or in addition to use of AD. This generates a warning on the CAS page; leave blank to disable static users
cas_users: casuser::Mellon,aaronson::password,jones::password,rutherford::password,syme::password,tparsons::password,charrington::password,wsmith::password,julia::password,obrien::password,bigbrother::password,bigbrother2::password

# This should be the hostname of the system cas is running on
cas_server_name: localhost