---
- name: add group "tomcat"
  group: name=tomcat
  become: True
  become_method: sudo

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Create Tomcat log folder
  file:
    path: /var/log/tomcat
    state: directory
    group: tomcat
    owner: tomcat
  become: true
  become_method: sudo

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.5/bin/apache-tomcat-8.5.5.tar.gz dest=/opt/apache-tomcat-8.5.5.tar.gz
  become: True
  become_method: sudo

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-8.5.5.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.5
  become: True
  become_method: sudo

- name: Symlink install directory
  file: src=/opt/apache-tomcat-8.5.5 path=/usr/share/tomcat state=link
  become: True
  become_method: sudo

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes
  become: True
  become_method: sudo

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat
  become: True
  become_method: sudo

- name: Install Tomcat server Keystore
  copy: src=.keystore dest=/usr/share/tomcat/conf/
  notify: restart tomcat
  become: True
  become_method: sudo

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat
  become: True
  become_method: sudo

- name: Configure Tomcat context
  template: src=context.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat
  become: True
  become_method: sudo

- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755
  become: True
  become_method: sudo

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes
  become: True
  become_method: sudo

- name: wait for tomcat to start
  wait_for: port={{https_port}}
  become: True
  become_method: sudo